name: visionary

services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "49322:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "49325:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "49327:9000"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: ["server", "/data"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  model:
    build:
      context: model
      dockerfile: Dockerfile
    container_name: model
    ports:
      - 49543:49543

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 49432:80

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - 49321:49321
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    command: ["sh", "-c", "bun run db:push:main && bun run start"]

volumes:
  postgres_data:
  redis_data:
  minio_data:
