services:
  model:
    build:
      context: ../model
      dockerfile: Dockerfile
    container_name: model
    restart: always
    ports:
      - 49543:49543

  local_db:
    image: postgres:17
    container_name: local_db
    restart: always
    env_file:
      - .env
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - local_db_data:/var/lib/postgresql/data

  test_db:
    image: postgres:17
    container_name: test_db
    restart: always
    env_file:
      - .env
    ports:
      - '49323:5432'
    environment:
      POSTGRES_DB: 'test_db'
      POSTGRES_USER: 'test_user'
      POSTGRES_PASSWORD: 'test_pass'
    volumes:
      - test_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - '49324:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pg@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'pgadmin'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - local_db
      - test_db

  redis:
    image: redis:8
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    env_file:
      - .env
    ports:
      - '49326:5540'
    environment:
      RI_REDIS_HOST: 'redis'
      RI_REDIS_PORT: '6379'
      RI_REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    env_file:
      - .env
    ports:
      - '49327:9000'
      - '49328:9090'
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: ['server', '/data', '--console-address', ':9090']

volumes:
  local_db_data:
  test_db_data:
  redis_data:
  minio_data:
